import Link from "next/link";
import { FileText, Files } from "lucide-react";
import { Card } from "@/components/ui/card";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card">
        <div className="container mx-auto p-4">
          <h1 className="text-2xl font-bold">Source Map 堆栈解析器</h1>
        </div>
      </header>
      <main className="container mx-auto p-4">
        <div className="flex flex-col lg:flex-row gap-6">
          <div className="lg:w-64 lg:flex-shrink-0">
            <Card className="p-4 shadow-lg border-0 bg-gradient-to-br from-background to-muted/20">
              <div className="flex flex-row lg:flex-col gap-4">
                <Link
                  href="/original-position-for/single"
                  className="flex-1 lg:flex-none h-12 text-base font-medium flex items-center justify-center rounded-md transition-colors"
                >
                  <FileText className="h-5 w-5 mr-2" />
                  <span className="hidden sm:inline">单文件解析</span>
                  <span className="sm:hidden">单文件</span>
                </Link>
                <Link
                  href="/original-position-for/multi"
                  className={
                    "flex-1 lg:flex-none h-12 text-base font-medium flex items-center justify-center rounded-md transition-colors"
                  }
                >
                  <Files className="h-5 w-5 mr-2" />
                  <span className="hidden sm:inline">多文件解析</span>
                  <span className="sm:hidden">多文件</span>
                </Link>
              </div>
            </Card>
          </div>
          <div className="flex-1">{children}</div>
        </div>
      </main>
    </div>
  );
}
