import type { Metadata } from "next";
import { Nav } from "@/features/original-position-for/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-card">
        <div className="container mx-auto p-4">
          <h1 className="text-2xl font-bold">Source Map Parser</h1>
        </div>
      </header>
      <main className="container mx-auto p-4">
        <div className="flex flex-col lg:flex-row gap-6">
          <div className="lg:w-64 lg:flex-shrink-0">
            <Nav />
          </div>
          <div className="flex-1">{children}</div>
        </div>
      </main>
    </div>
  );
}
